version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db_nodejs
    restart: always
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: